name: 'Test'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - name: Run prettier
        if: startsWith(matrix.os, 'ubuntu-24.04')
        run: bun run format:check

      - name: Run eslint
        if: startsWith(matrix.os, 'ubuntu-24.04')
        run: bun run lint

      - name: Run build
        if: startsWith(matrix.os, 'ubuntu-24.04')
        run: bun run build

      - run: bun test
